"""
universe_generation.py — Hollow Firmament galaxy initialization.

Builds a tree of orbital bodies (mobile diagram) for each star system:

    Primary Star (root, no orbit)
      ├─ Secondary Star (wide orbit around primary)
      ├─ Planet
      │    ├─ Moon
      │    └─ Moon
      ├─ Planet
      └─ Planet

The key constraint: siblings at each level cannot have crossing orbits.
Eccentricity is assigned after orbit radii, capped so apoapsis(i) < periapsis(i+1).

Moons are constrained to stay within their parent's Hill sphere
(approximated as a fraction of the gap to adjacent orbits).
"""

import math
import os
import random
import psycopg2
from psycopg2.extras import execute_values

# ── Configuration ───────────────────────────────────────────

GALAXY_SEED = 42
NUM_SYSTEMS = 120
GALAXY_EXTENT = 10000.0
GALAXY_OFFSET = 1000.0

DB_CONFIG = {
    "dbname": "spacegame",
    "user": "postgres",
    "password": "postgres",
    "host": "localhost",
    "port": 5432,
}

# ── Stellar Data ────────────────────────────────────────────
#
# Main-sequence stars use the standard Harvard classification.
# Weights approximate the real initial mass function (IMF).
#
# Compact remnants and brown dwarfs are generated separately —
# they aren't drawn from the same IMF but occur as companions
# or evolved primaries at realistic frequencies.

MAIN_SEQUENCE = [
    {"class": "O", "color": "#9BB0FF", "temp": (30000, 50000), "mass": (16, 60),     "lum": (30000, 500000), "radius": (6.6, 15),   "weight": 1},
    {"class": "B", "color": "#AABFFF", "temp": (10000, 30000), "mass": (2.1, 16),    "lum": (25, 30000),     "radius": (1.8, 6.6),  "weight": 3},
    {"class": "A", "color": "#CAD7FF", "temp": (7500, 10000),  "mass": (1.4, 2.1),   "lum": (5, 25),         "radius": (1.4, 1.8),  "weight": 6},
    {"class": "F", "color": "#F8F7FF", "temp": (6000, 7500),   "mass": (1.04, 1.4),  "lum": (1.5, 5),        "radius": (1.15, 1.4), "weight": 10},
    {"class": "G", "color": "#FFF4E0", "temp": (5200, 6000),   "mass": (0.8, 1.04),  "lum": (0.6, 1.5),      "radius": (0.96, 1.15),"weight": 15},
    {"class": "K", "color": "#FFD2A1", "temp": (3700, 5200),   "mass": (0.45, 0.8),  "lum": (0.08, 0.6),     "radius": (0.7, 0.96), "weight": 25},
    {"class": "M", "color": "#FF6347", "temp": (2400, 3700),   "mass": (0.08, 0.45), "lum": (0.001, 0.08),    "radius": (0.1, 0.7), "weight": 40},
]

# Non-main-sequence stellar types (generated by make_exotic_star)
EXOTIC_TYPES = {
    "brown_dwarf":  {"class": "L/T", "color": "#8B4513", "temp": (500, 2400),  "mass": (0.013, 0.08), "lum": (0.00001, 0.001), "radius": (0.08, 0.12)},
    "white_dwarf":  {"class": "WD",  "color": "#E8E8FF", "temp": (4000, 40000),"mass": (0.5, 1.4),    "lum": (0.0001, 0.01),   "radius": (0.008, 0.02)},
    "neutron_star": {"class": "NS",  "color": "#C0C0FF", "temp": (500000, 1000000), "mass": (1.1, 2.3),"lum": (0.00001, 0.1),   "radius": (0.00001, 0.00002)},
    "black_hole":   {"class": "BH",  "color": "#1A0A2E", "temp": (0, 0),       "mass": (3, 50),       "lum": (0, 0),            "radius": (0.00001, 0.00005)},
}

# Multiplicity distribution (observed: ~55% single, ~33% binary, etc.)
# For up to 6 stars. Higher multiplicities are very rare but observed.
# n_companions → probability (cumulative thresholds)
MULTIPLICITY = [
    (0, 0.55),   # single
    (1, 0.88),   # binary   (~33%)
    (2, 0.96),   # trinary  (~8%)
    (3, 0.99),   # quaternary (~3%)
    (4, 0.998),  # quintuple (~0.8%)
    (5, 1.0),    # sextuple (~0.2%)
]

PLANET_TYPES = [
    {"type": "Gas Giant",   "color": "#D4A574", "r": (18, 32)},
    {"type": "Ice Giant",   "color": "#7EC8E3", "r": (14, 22)},
    {"type": "Terrestrial", "color": "#6B8E23", "r": (6, 12)},
    {"type": "Rocky",       "color": "#A0522D", "r": (5, 10)},
    {"type": "Ocean World", "color": "#4682B4", "r": (8, 14)},
    {"type": "Volcanic",    "color": "#CC4400", "r": (5, 9)},
]

MOON_TYPES = [
    {"type": "Rocky Moon",  "color": "#888888", "r": (2, 5)},
    {"type": "Ice Moon",    "color": "#B0D0E8", "r": (2, 6)},
    {"type": "Barren Moon", "color": "#666050", "r": (1, 4)},
    {"type": "Volcanic Moon","color": "#AA5522", "r": (2, 4)},
]

# ── Helpers ─────────────────────────────────────────────────

def rand(rng, lo, hi):
    return lo + rng.random() * (hi - lo)

def weighted_choice(rng, items):
    total = sum(it["weight"] for it in items)
    r = rng.random() * total
    acc = 0
    for it in items:
        acc += it["weight"]
        if r <= acc:
            return it
    return items[-1]

def assign_eccentricities(rng, bodies, max_ecc=0.35):
    """Assign eccentricities to a list of sibling bodies (sorted by semi_major)
    such that no two orbits cross. Modifies bodies in place."""
    n = len(bodies)
    radii = [b["semi_major"] for b in bodies]

    for i in range(n):
        desired = rng.random() * max_ecc
        a = radii[i]

        # Apoapsis must not reach next orbit (10% buffer)
        if i < n - 1:
            max_out = (radii[i + 1] * 0.9 / a) - 1
        else:
            max_out = max_ecc

        # Periapsis must not reach previous orbit's apoapsis (10% buffer)
        if i > 0:
            prev_apo = radii[i - 1] * (1 + bodies[i - 1]["eccentricity"])
            max_in = 1 - (prev_apo * 1.1 / a)
        else:
            max_in = max_ecc

        bodies[i]["eccentricity"] = round(max(0, min(desired, max_out, max_in)), 4)

# ── Body Generators ─────────────────────────────────────────

def _star_body(rng, system_id, spec):
    """Build a star body dict from a spectral data dict."""
    return {
        "system_id": system_id,
        "body_type": "star",
        "spectral_class": spec["class"],
        "mass": round(rand(rng, *spec["mass"]), 4),
        "luminosity": round(rand(rng, *spec["lum"]), 4),
        "temperature": int(rand(rng, *spec["temp"])) if spec["temp"][1] > 0 else 0,
        "radius": round(rand(rng, *spec["radius"]), 6),
        "color_hex": spec["color"],
        "seed": rng.randint(0, 2**31 - 1),
        "planet_type": None,
        "population": 0,
        "minerals_rate": 0, "biomass_rate": 0, "gas_rate": 0, "energy_rate": 0,
    }

def make_star(rng, system_id):
    """Generate a main-sequence star from the IMF."""
    return _star_body(rng, system_id, weighted_choice(rng, MAIN_SEQUENCE))

def make_exotic_star(rng, system_id, kind):
    """Generate an exotic stellar object: brown_dwarf, white_dwarf, neutron_star, black_hole."""
    return _star_body(rng, system_id, EXOTIC_TYPES[kind])

def make_companion(rng, system_id):
    """Generate a companion star. Usually main-sequence, occasionally exotic.
    
    Observed frequencies for companions (rough):
      ~70% main-sequence (often lower-mass than primary)
      ~15% white dwarf
      ~10% brown dwarf
      ~4%  neutron star
      ~1%  black hole
    """
    roll = rng.random()
    if roll < 0.70:
        return make_star(rng, system_id)
    elif roll < 0.85:
        return make_exotic_star(rng, system_id, "white_dwarf")
    elif roll < 0.95:
        return make_exotic_star(rng, system_id, "brown_dwarf")
    elif roll < 0.99:
        return make_exotic_star(rng, system_id, "neutron_star")
    else:
        return make_exotic_star(rng, system_id, "black_hole")

def make_planet(rng, system_id, star_luminosity, orbit_radius):
    """Generate a planet body dict at a given orbit radius."""
    # Habitable zone (display units)
    hz_in = 175 * math.sqrt(max(star_luminosity, 0.001)) * 0.85
    hz_out = 175 * math.sqrt(max(star_luminosity, 0.001)) * 1.5

    if orbit_radius < hz_in:
        weights = [2, 1, 3, 8, 1, 10]  # inner: rocky/volcanic
    elif orbit_radius <= hz_out:
        weights = [2, 2, 10, 3, 8, 1]  # habitable: terrestrial/ocean
    else:
        weights = [10, 8, 2, 3, 2, 1]  # outer: gas/ice giants

    pt = PLANET_TYPES[rng.choices(range(len(PLANET_TYPES)), weights=weights, k=1)[0]]

    if pt["type"] in ("Terrestrial", "Ocean World"):
        pop = rng.randint(500, 15000)
    elif pt["type"] == "Rocky":
        pop = rng.randint(0, 2000)
    else:
        pop = rng.randint(0, 500)

    return {
        "system_id": system_id,
        "body_type": "planet",
        "planet_type": pt["type"],
        "radius": round(rand(rng, *pt["r"]), 2),
        "color_hex": pt["color"],
        "mass": round(rand(rng, 0.1, 300), 2),  # Earth masses (placeholder)
        "seed": rng.randint(0, 2**31 - 1),
        "spectral_class": None, "luminosity": None, "temperature": None,
        "population": pop,
        "minerals_rate": round(rng.random() * 5, 2),
        "biomass_rate": round(rng.random() * 3, 2),
        "gas_rate": round(rng.random() * 4, 2),
        "energy_rate": round(rng.random() * 6, 2),
    }

def make_moon(rng, system_id):
    """Generate a moon body dict."""
    mt = rng.choice(MOON_TYPES)
    return {
        "system_id": system_id,
        "body_type": "moon",
        "planet_type": mt["type"],
        "radius": round(rand(rng, *mt["r"]), 2),
        "color_hex": mt["color"],
        "mass": round(rng.random() * 0.5, 4),
        "seed": rng.randint(0, 2**31 - 1),
        "spectral_class": None, "luminosity": None, "temperature": None,
        "population": rng.randint(0, 500) if rng.random() < 0.3 else 0,
        "minerals_rate": round(rng.random() * 2, 2),
        "biomass_rate": round(rng.random() * 1, 2),
        "gas_rate": round(rng.random() * 0.5, 2),
        "energy_rate": round(rng.random() * 1.5, 2),
    }

# ── System Builder ──────────────────────────────────────────

def generate_system_bodies(rng, system_id):
    """Build the full mobile tree for one star system.
    
    Returns a flat list of body dicts. The tree:
      1. Primary star (root) — usually main-sequence, rarely exotic
      2. 0-5 companion stars on wide orbits
      3. Planets per star (fewer around compact/exotic objects)
      4. Moons per planet (within Hill sphere)
    
    Constraint: no system may contain ONLY brown dwarfs.
    """
    bodies = []

    # ── Primary star ────────────────────────────────────────
    # ~5% chance the primary is an evolved/exotic object
    # (represents old systems where the primary has evolved)
    roll = rng.random()
    if roll < 0.03:
        primary = make_exotic_star(rng, system_id, "white_dwarf")
    elif roll < 0.045:
        primary = make_exotic_star(rng, system_id, "neutron_star")
    elif roll < 0.05:
        primary = make_exotic_star(rng, system_id, "black_hole")
    else:
        primary = make_star(rng, system_id)

    primary["name"] = f"S{system_id}-0"
    primary["parent_index"] = None
    primary["semi_major"] = None
    primary["eccentricity"] = 0
    primary["orbit_angle"] = 0
    bodies.append(primary)
    primary_idx = 0

    # ── Companion stars ─────────────────────────────────────
    # Multiplicity from observed distributions (up to 6 total)
    mult_roll = rng.random()
    num_companions = 0
    for n, threshold in MULTIPLICITY:
        if mult_roll < threshold:
            num_companions = n
            break

    companion_orbit_base = 800
    companion_stars = []
    for ci in range(num_companions):
        comp = make_companion(rng, system_id)
        comp["name"] = f"S{system_id}-{ci + 1}"
        comp["parent_index"] = primary_idx
        comp["semi_major"] = round(companion_orbit_base + rng.random() * 400, 2)
        comp["eccentricity"] = 0
        comp["orbit_angle"] = round(rng.random() * math.pi * 2, 4)
        companion_stars.append(comp)
        companion_orbit_base = comp["semi_major"] + 300

    if companion_stars:
        assign_eccentricities(rng, companion_stars, max_ecc=0.25)

    # ── No brown-dwarf-only systems ─────────────────────────
    all_stars = [primary] + companion_stars
    if all(s["spectral_class"] == "L/T" for s in all_stars):
        # Promote the primary to a random main-sequence star
        spec = weighted_choice(rng, MAIN_SEQUENCE)
        for key in ("spectral_class", "color_hex"):
            primary[key] = spec[key] if key != "color_hex" else spec["color"]
        primary["spectral_class"] = spec["class"]
        primary["mass"] = round(rand(rng, *spec["mass"]), 4)
        primary["luminosity"] = round(rand(rng, *spec["lum"]), 4)
        primary["temperature"] = int(rand(rng, *spec["temp"]))
        primary["radius"] = round(rand(rng, *spec["radius"]), 4)
        primary["color_hex"] = spec["color"]

    # ── Planets per star ────────────────────────────────────
    stars_with_indices = [(primary, primary_idx)]
    for comp in companion_stars:
        bodies.append(comp)
        stars_with_indices.append((comp, len(bodies) - 1))

    for star, star_idx in stars_with_indices:
        lum = star.get("luminosity") or 0
        sc = star.get("spectral_class", "")

        # Compact remnants and brown dwarfs get fewer/no planets
        if sc in ("BH", "NS"):
            num_planets = rng.choices([0, 1, 2], weights=[70, 20, 10], k=1)[0]
        elif sc == "WD":
            num_planets = rng.choices([0, 1, 2, 3], weights=[40, 30, 20, 10], k=1)[0]
        elif sc == "L/T":
            num_planets = rng.choices([0, 1, 2], weights=[50, 35, 15], k=1)[0]
        elif star_idx == primary_idx:
            num_planets = rng.randint(3, 8)
        else:
            num_planets = rng.randint(0, 3)

        orbit_base = 140.0
        planet_entries = []
        for pi in range(num_planets):
            orbit_r = orbit_base + 52 + rng.random() * 123
            orbit_base = orbit_r

            planet = make_planet(rng, system_id, max(lum, 0.001), orbit_r)
            planet["name"] = f"P{system_id}-{star_idx}.{pi}"
            planet["parent_index"] = star_idx
            planet["semi_major"] = round(orbit_r, 2)
            planet["eccentricity"] = 0
            planet["orbit_angle"] = round(rng.random() * math.pi * 2, 4)
            planet_entries.append(planet)

        if planet_entries:
            assign_eccentricities(rng, planet_entries)

        for pi, planet in enumerate(planet_entries):
            bodies.append(planet)
            planet_idx = len(bodies) - 1
            _generate_moons(rng, system_id, planet, planet_idx,
                            planet_entries, pi, bodies)

    return bodies


def _generate_moons(rng, system_id, planet, planet_idx, siblings, sib_index, bodies):
    """Generate moons for a planet, constrained to its Hill sphere.
    
    Moon orbits are planet-relative (measured from planet center).
    The available zone is a fraction of the gap to neighboring orbits.
    Moons are spaced evenly across this zone with jitter.
    """
    ptype = planet.get("planet_type", "")

    # Moon counts inspired by our solar system:
    # Jupiter ~95, Saturn ~146, Uranus ~27, Neptune ~16, Earth 1, Mars 2
    if "Gas Giant" in ptype:
        num_moons = rng.choices([1, 2, 3, 4, 5, 6, 7, 8],
                                weights=[5, 10, 15, 20, 20, 15, 10, 5], k=1)[0]
    elif "Ice Giant" in ptype:
        num_moons = rng.choices([0, 1, 2, 3, 4, 5],
                                weights=[5, 10, 20, 25, 25, 15], k=1)[0]
    elif ptype in ("Terrestrial", "Ocean World"):
        num_moons = rng.choices([0, 1, 2, 3], weights=[30, 40, 20, 10], k=1)[0]
    elif ptype == "Rocky":
        num_moons = rng.choices([0, 1, 2], weights=[50, 35, 15], k=1)[0]
    else:
        num_moons = rng.choices([0, 1], weights=[70, 30], k=1)[0]

    if num_moons == 0:
        return

    # Compute available moon zone from gaps to neighboring planet orbits
    a = planet["semi_major"]
    ecc = planet["eccentricity"]
    periapsis = a * (1 - ecc)
    apoapsis = a * (1 + ecc)

    if sib_index > 0:
        prev = siblings[sib_index - 1]
        gap_in = periapsis - prev["semi_major"] * (1 + prev["eccentricity"])
    else:
        gap_in = periapsis * 0.5

    if sib_index < len(siblings) - 1:
        nxt = siblings[sib_index + 1]
        gap_out = nxt["semi_major"] * (1 - nxt["eccentricity"]) - apoapsis
    else:
        gap_out = a * 0.5

    # Hill sphere ≈ 40% of the larger gap (generous — real Hill spheres
    # can be ~1/3 of the orbit radius, which is usually bigger than this)
    hill = max(gap_in, gap_out) * 0.4
    # Floor: at least 3x the planet's display radius
    max_moon_orbit = max(hill, planet["radius"] * 3)

    # Moon zone: from just outside Roche limit to Hill sphere edge
    inner_edge = planet["radius"] * 1.5
    zone_size = max_moon_orbit - inner_edge
    if zone_size < 3:
        return  # no room

    # Spread moons evenly with jitter
    moon_entries = []
    for mi in range(num_moons):
        t = (mi + 0.3 + rng.random() * 0.4) / num_moons
        slot = inner_edge + zone_size * t
        if slot > max_moon_orbit:
            break

        moon = make_moon(rng, system_id)
        moon["name"] = f"M{system_id}-{planet_idx}.{mi}"
        moon["parent_index"] = planet_idx
        moon["semi_major"] = round(slot, 2)
        moon["eccentricity"] = 0
        moon["orbit_angle"] = round(rng.random() * math.pi * 2, 4)
        moon_entries.append(moon)

    if moon_entries:
        assign_eccentricities(rng, moon_entries, max_ecc=0.1)
        bodies.extend(moon_entries)


# ── Galaxy Generator ────────────────────────────────────────

def generate_universe(galaxy_seed=GALAXY_SEED):
    """Generate all systems with their body trees."""
    master = random.Random(galaxy_seed)
    systems = []
    all_bodies = []  # flat list with parent_index references

    for i in range(NUM_SYSTEMS):
        sys_seed = master.randint(0, 2**31 - 1)
        sys_rng = random.Random(sys_seed)

        system = {
            "id": i + 1,
            "name": f"System-{i + 1}",
            "galaxy_x": round(GALAXY_OFFSET + master.random() * GALAXY_EXTENT, 2),
            "galaxy_y": round(GALAXY_OFFSET + master.random() * GALAXY_EXTENT, 2),
            "seed": sys_seed,
        }
        systems.append(system)

        bodies = generate_system_bodies(sys_rng, system["id"])
        # Tag each body with its offset so we can resolve parent_index → parent_id later
        base_offset = len(all_bodies)
        for b in bodies:
            b["_offset"] = base_offset
        all_bodies.extend(bodies)

    return systems, all_bodies


# ── Database ────────────────────────────────────────────────

def init_database(conn):
    schema_path = os.path.join(os.path.dirname(__file__), "schema.sql")
    with open(schema_path) as f:
        sql = f.read()
    with conn.cursor() as cur:
        cur.execute(sql)
    conn.commit()
    print("[✓] Schema created")


def populate_database(conn, systems, all_bodies):
    with conn.cursor() as cur:
        # Player
        cur.execute("INSERT INTO players (username) VALUES (%s) RETURNING id", ("TestPlayer",))
        player_id = cur.fetchone()[0]

        # Systems
        execute_values(cur,
            "INSERT INTO systems (id, name, galaxy_x, galaxy_y, seed) VALUES %s",
            [(s["id"], s["name"], s["galaxy_x"], s["galaxy_y"], s["seed"]) for s in systems])
        cur.execute(f"SELECT setval('systems_id_seq', {len(systems)})")

        # Bodies: insert in order (parents before children) and track DB IDs
        db_ids = {}  # list_index → DB id
        for i, b in enumerate(all_bodies):
            parent_db_id = None
            if b["parent_index"] is not None:
                parent_list_idx = b["_offset"] + b["parent_index"]
                parent_db_id = db_ids.get(parent_list_idx)

            cur.execute("""
                INSERT INTO bodies (
                    system_id, parent_id, body_type, name,
                    semi_major, eccentricity, orbit_angle,
                    mass, radius, color_hex, seed,
                    spectral_class, luminosity, temperature,
                    planet_type,
                    population, minerals_rate, biomass_rate, gas_rate, energy_rate
                ) VALUES (%s,%s,%s,%s, %s,%s,%s, %s,%s,%s,%s, %s,%s,%s, %s, %s,%s,%s,%s,%s)
                RETURNING id
            """, (
                b["system_id"], parent_db_id, b["body_type"], b["name"],
                b["semi_major"], b["eccentricity"], b["orbit_angle"],
                b["mass"], b["radius"], b["color_hex"], b["seed"],
                b.get("spectral_class"), b.get("luminosity"), b.get("temperature"),
                b.get("planet_type"),
                b["population"], b["minerals_rate"], b["biomass_rate"],
                b["gas_rate"], b["energy_rate"],
            ))
            db_ids[i] = cur.fetchone()[0]

        # System resources
        execute_values(cur,
            "INSERT INTO system_resources (system_id, controlled_by_player_id, minerals, biomass, gas, energy) VALUES %s",
            [(s["id"], player_id, 0, 0, 0, 0) for s in systems])

    conn.commit()

    stars = sum(1 for b in all_bodies if b["body_type"] == "star")
    planets = sum(1 for b in all_bodies if b["body_type"] == "planet")
    moons = sum(1 for b in all_bodies if b["body_type"] == "moon")
    print(f"[✓] Inserted {len(systems)} systems, {stars} stars, {planets} planets, {moons} moons")


def main():
    print("═══════════════════════════════════════════")
    print("  Hollow Firmament — Universe Generation   ")
    print("═══════════════════════════════════════════")
    print(f"Galaxy seed: {GALAXY_SEED}")
    print(f"Generating {NUM_SYSTEMS} systems...")

    systems, all_bodies = generate_universe(GALAXY_SEED)

    stars = sum(1 for b in all_bodies if b["body_type"] == "star")
    planets = sum(1 for b in all_bodies if b["body_type"] == "planet")
    moons = sum(1 for b in all_bodies if b["body_type"] == "moon")
    print(f"  → {stars} stars, {planets} planets, {moons} moons")

    print("Connecting to PostgreSQL...")
    conn = psycopg2.connect(**DB_CONFIG)
    try:
        init_database(conn)
        populate_database(conn, systems, all_bodies)
    finally:
        conn.close()

    print("[✓] Universe initialized!")

if __name__ == "__main__":
    main()